sh createTestCases.sh
sh createIndexes.sh
sh summarizeData.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh executeRC.sh
sh summarizeData.sh
sh avgData.sh
