cat 1/fts_all.result 2/fts_all.result 3/fts_all.result 4/fts_all.result 5/fts_all.result 6/fts_all.result 7/fts_all.result 8/fts_all.result 9/fts_all.result 10/fts_all.result 11/fts_all.result 12/fts_all.result 13/fts_all.result 14/fts_all.result 15/fts_all.result 16/fts_all.result 17/fts_all.result 18/fts_all.result 19/fts_all.result 20/fts_all.result 21/fts_all.result 22/fts_all.result 23/fts_all.result 24/fts_all.result 25/fts_all.result 26/fts_all.result 27/fts_all.result 28/fts_all.result 29/fts_all.result 30/fts_all.result 31/fts_all.result 32/fts_all.result 33/fts_all.result 34/fts_all.result 35/fts_all.result 36/fts_all.result 37/fts_all.result 38/fts_all.result 39/fts_all.result 40/fts_all.result 41/fts_all.result 42/fts_all.result 43/fts_all.result 44/fts_all.result 45/fts_all.result 46/fts_all.result 47/fts_all.result 48/fts_all.result 49/fts_all.result 50/fts_all.result 51/fts_all.result 52/fts_all.result 53/fts_all.result 54/fts_all.result 55/fts_all.result 56/fts_all.result 57/fts_all.result 58/fts_all.result 59/fts_all.result 60/fts_all.result 61/fts_all.result 62/fts_all.result 63/fts_all.result 64/fts_all.result 65/fts_all.result 66/fts_all.result 67/fts_all.result 68/fts_all.result 69/fts_all.result 70/fts_all.result 71/fts_all.result 72/fts_all.result 73/fts_all.result 74/fts_all.result 75/fts_all.result 76/fts_all.result 77/fts_all.result 78/fts_all.result 79/fts_all.result 80/fts_all.result 81/fts_all.result 82/fts_all.result 83/fts_all.result 84/fts_all.result 85/fts_all.result 86/fts_all.result 87/fts_all.result 88/fts_all.result 89/fts_all.result 90/fts_all.result > fts_all.result
cat 1/fts_any.result 2/fts_any.result 3/fts_any.result 4/fts_any.result 5/fts_any.result 6/fts_any.result 7/fts_any.result 8/fts_any.result 9/fts_any.result 10/fts_any.result 11/fts_any.result 12/fts_any.result 13/fts_any.result 14/fts_any.result 15/fts_any.result 16/fts_any.result 17/fts_any.result 18/fts_any.result 19/fts_any.result 20/fts_any.result 21/fts_any.result 22/fts_any.result 23/fts_any.result 24/fts_any.result 25/fts_any.result 26/fts_any.result 27/fts_any.result 28/fts_any.result 29/fts_any.result 30/fts_any.result 31/fts_any.result 32/fts_any.result 33/fts_any.result 34/fts_any.result 35/fts_any.result 36/fts_any.result 37/fts_any.result 38/fts_any.result 39/fts_any.result 40/fts_any.result 41/fts_any.result 42/fts_any.result 43/fts_any.result 44/fts_any.result 45/fts_any.result 46/fts_any.result 47/fts_any.result 48/fts_any.result 49/fts_any.result 50/fts_any.result 51/fts_any.result 52/fts_any.result 53/fts_any.result 54/fts_any.result 55/fts_any.result 56/fts_any.result 57/fts_any.result 58/fts_any.result 59/fts_any.result 60/fts_any.result 61/fts_any.result 62/fts_any.result 63/fts_any.result 64/fts_any.result 65/fts_any.result 66/fts_any.result 67/fts_any.result 68/fts_any.result 69/fts_any.result 70/fts_any.result 71/fts_any.result 72/fts_any.result 73/fts_any.result 74/fts_any.result 75/fts_any.result 76/fts_any.result 77/fts_any.result 78/fts_any.result 79/fts_any.result 80/fts_any.result 81/fts_any.result 82/fts_any.result 83/fts_any.result 84/fts_any.result 85/fts_any.result 86/fts_any.result 87/fts_any.result 88/fts_any.result 89/fts_any.result 90/fts_any.result > fts_any.result
cat 1/index_all.result 2/index_all.result 3/index_all.result 4/index_all.result 5/index_all.result 6/index_all.result 7/index_all.result 8/index_all.result 9/index_all.result 10/index_all.result 11/index_all.result 12/index_all.result 13/index_all.result 14/index_all.result 15/index_all.result 16/index_all.result 17/index_all.result 18/index_all.result 19/index_all.result 20/index_all.result 21/index_all.result 22/index_all.result 23/index_all.result 24/index_all.result 25/index_all.result 26/index_all.result 27/index_all.result 28/index_all.result 29/index_all.result 30/index_all.result 31/index_all.result 32/index_all.result 33/index_all.result 34/index_all.result 35/index_all.result 36/index_all.result 37/index_all.result 38/index_all.result 39/index_all.result 40/index_all.result 41/index_all.result 42/index_all.result 43/index_all.result 44/index_all.result 45/index_all.result 46/index_all.result 47/index_all.result 48/index_all.result 49/index_all.result 50/index_all.result 51/index_all.result 52/index_all.result 53/index_all.result 54/index_all.result 55/index_all.result 56/index_all.result 57/index_all.result 58/index_all.result 59/index_all.result 60/index_all.result 61/index_all.result 62/index_all.result 63/index_all.result 64/index_all.result 65/index_all.result 66/index_all.result 67/index_all.result 68/index_all.result 69/index_all.result 70/index_all.result 71/index_all.result 72/index_all.result 73/index_all.result 74/index_all.result 75/index_all.result 76/index_all.result 77/index_all.result 78/index_all.result 79/index_all.result 80/index_all.result 81/index_all.result 82/index_all.result 83/index_all.result 84/index_all.result 85/index_all.result 86/index_all.result 87/index_all.result 88/index_all.result 89/index_all.result 90/index_all.result > index_all.result

cat 1/index_any.result 2/index_any.result 3/index_any.result 4/index_any.result 5/index_any.result 6/index_any.result 7/index_any.result 8/index_any.result 9/index_any.result 10/index_any.result 11/index_any.result 12/index_any.result 13/index_any.result 14/index_any.result 15/index_any.result 16/index_any.result 17/index_any.result 18/index_any.result 19/index_any.result 20/index_any.result 21/index_any.result 22/index_any.result 23/index_any.result 24/index_any.result 25/index_any.result 26/index_any.result 27/index_any.result 28/index_any.result 29/index_any.result 30/index_any.result 31/index_any.result 32/index_any.result 33/index_any.result 34/index_any.result 35/index_any.result 36/index_any.result 37/index_any.result 38/index_any.result 39/index_any.result 40/index_any.result 41/index_any.result 42/index_any.result 43/index_any.result 44/index_any.result 45/index_any.result 46/index_any.result 47/index_any.result 48/index_any.result 49/index_any.result 50/index_any.result 51/index_any.result 52/index_any.result 53/index_any.result 54/index_any.result 55/index_any.result 56/index_any.result 57/index_any.result 58/index_any.result 59/index_any.result 60/index_any.result 61/index_any.result 62/index_any.result 63/index_any.result 64/index_any.result 65/index_any.result 66/index_any.result 67/index_any.result 68/index_any.result 69/index_any.result 70/index_any.result 71/index_any.result 72/index_any.result 73/index_any.result 74/index_any.result 75/index_any.result 76/index_any.result 77/index_any.result 78/index_any.result 79/index_any.result 80/index_any.result 81/index_any.result 82/index_any.result 83/index_any.result 84/index_any.result 85/index_any.result 86/index_any.result 87/index_any.result 88/index_any.result 89/index_any.result 90/index_any.result > index_any.result

rm 1/fts_all.result
rm 1/fts_any.result
rm 1/index_all.result
rm 1/index_any.result
rm 2/fts_all.result
rm 2/fts_any.result
rm 2/index_all.result
rm 2/index_any.result
rm 3/fts_all.result
rm 3/fts_any.result
rm 3/index_all.result
rm 3/index_any.result
rm 4/fts_all.result
rm 4/fts_any.result
rm 4/index_all.result
rm 4/index_any.result
rm 5/fts_all.result
rm 5/fts_any.result
rm 5/index_all.result
rm 5/index_any.result
rm 6/fts_all.result
rm 6/fts_any.result
rm 6/index_all.result
rm 6/index_any.result
rm 7/fts_all.result
rm 7/fts_any.result
rm 7/index_all.result
rm 7/index_any.result
rm 8/fts_all.result
rm 8/fts_any.result
rm 8/index_all.result
rm 8/index_any.result
rm 9/fts_all.result
rm 9/fts_any.result
rm 9/index_all.result
rm 9/index_any.result
rm 10/fts_all.result
rm 10/fts_any.result
rm 10/index_all.result
rm 10/index_any.result
rm 11/fts_all.result
rm 11/fts_any.result
rm 11/index_all.result
rm 11/index_any.result
rm 12/fts_all.result
rm 12/fts_any.result
rm 12/index_all.result
rm 12/index_any.result
rm 13/fts_all.result
rm 13/fts_any.result
rm 13/index_all.result
rm 13/index_any.result
rm 14/fts_all.result
rm 14/fts_any.result
rm 14/index_all.result
rm 14/index_any.result
rm 15/fts_all.result
rm 15/fts_any.result
rm 15/index_all.result
rm 15/index_any.result
rm 16/fts_all.result
rm 16/fts_any.result
rm 16/index_all.result
rm 16/index_any.result
rm 17/fts_all.result
rm 17/fts_any.result
rm 17/index_all.result
rm 17/index_any.result
rm 18/fts_all.result
rm 18/fts_any.result
rm 18/index_all.result
rm 18/index_any.result
rm 19/fts_all.result
rm 19/fts_any.result
rm 19/index_all.result
rm 19/index_any.result
rm 20/fts_all.result
rm 20/fts_any.result
rm 20/index_all.result
rm 20/index_any.result
rm 21/fts_all.result
rm 21/fts_any.result
rm 21/index_all.result
rm 21/index_any.result
rm 22/fts_all.result
rm 22/fts_any.result
rm 22/index_all.result
rm 22/index_any.result
rm 23/fts_all.result
rm 23/fts_any.result
rm 23/index_all.result
rm 23/index_any.result
rm 24/fts_all.result
rm 24/fts_any.result
rm 24/index_all.result
rm 24/index_any.result
rm 25/fts_all.result
rm 25/fts_any.result
rm 25/index_all.result
rm 25/index_any.result
rm 26/fts_all.result
rm 26/fts_any.result
rm 26/index_all.result
rm 26/index_any.result
rm 27/fts_all.result
rm 27/fts_any.result
rm 27/index_all.result
rm 27/index_any.result
rm 28/fts_all.result
rm 28/fts_any.result
rm 28/index_all.result
rm 28/index_any.result
rm 29/fts_all.result
rm 29/fts_any.result
rm 29/index_all.result
rm 29/index_any.result
rm 30/fts_all.result
rm 30/fts_any.result
rm 30/index_all.result
rm 30/index_any.result
rm 31/fts_all.result
rm 31/fts_any.result
rm 31/index_all.result
rm 31/index_any.result
rm 32/fts_all.result
rm 32/fts_any.result
rm 32/index_all.result
rm 32/index_any.result
rm 33/fts_all.result
rm 33/fts_any.result
rm 33/index_all.result
rm 33/index_any.result
rm 34/fts_all.result
rm 34/fts_any.result
rm 34/index_all.result
rm 34/index_any.result
rm 35/fts_all.result
rm 35/fts_any.result
rm 35/index_all.result
rm 35/index_any.result
rm 36/fts_all.result
rm 36/fts_any.result
rm 36/index_all.result
rm 36/index_any.result
rm 37/fts_all.result
rm 37/fts_any.result
rm 37/index_all.result
rm 37/index_any.result
rm 38/fts_all.result
rm 38/fts_any.result
rm 38/index_all.result
rm 38/index_any.result
rm 39/fts_all.result
rm 39/fts_any.result
rm 39/index_all.result
rm 39/index_any.result
rm 40/fts_all.result
rm 40/fts_any.result
rm 40/index_all.result
rm 40/index_any.result
rm 41/fts_all.result
rm 41/fts_any.result
rm 41/index_all.result
rm 41/index_any.result
rm 42/fts_all.result
rm 42/fts_any.result
rm 42/index_all.result
rm 42/index_any.result
rm 43/fts_all.result
rm 43/fts_any.result
rm 43/index_all.result
rm 43/index_any.result
rm 44/fts_all.result
rm 44/fts_any.result
rm 44/index_all.result
rm 44/index_any.result
rm 45/fts_all.result
rm 45/fts_any.result
rm 45/index_all.result
rm 45/index_any.result
rm 46/fts_all.result
rm 46/fts_any.result
rm 46/index_all.result
rm 46/index_any.result
rm 47/fts_all.result
rm 47/fts_any.result
rm 47/index_all.result
rm 47/index_any.result
rm 48/fts_all.result
rm 48/fts_any.result
rm 48/index_all.result
rm 48/index_any.result
rm 49/fts_all.result
rm 49/fts_any.result
rm 49/index_all.result
rm 49/index_any.result
rm 50/fts_all.result
rm 50/fts_any.result
rm 50/index_all.result
rm 50/index_any.result
rm 51/fts_all.result
rm 51/fts_any.result
rm 51/index_all.result
rm 51/index_any.result
rm 52/fts_all.result
rm 52/fts_any.result
rm 52/index_all.result
rm 52/index_any.result
rm 53/fts_all.result
rm 53/fts_any.result
rm 53/index_all.result
rm 53/index_any.result
rm 54/fts_all.result
rm 54/fts_any.result
rm 54/index_all.result
rm 54/index_any.result
rm 55/fts_all.result
rm 55/fts_any.result
rm 55/index_all.result
rm 55/index_any.result
rm 56/fts_all.result
rm 56/fts_any.result
rm 56/index_all.result
rm 56/index_any.result
rm 57/fts_all.result
rm 57/fts_any.result
rm 57/index_all.result
rm 57/index_any.result
rm 58/fts_all.result
rm 58/fts_any.result
rm 58/index_all.result
rm 58/index_any.result
rm 59/fts_all.result
rm 59/fts_any.result
rm 59/index_all.result
rm 59/index_any.result
rm 60/fts_all.result
rm 60/fts_any.result
rm 60/index_all.result
rm 60/index_any.result
rm 61/fts_all.result
rm 61/fts_any.result
rm 61/index_all.result
rm 61/index_any.result
rm 62/fts_all.result
rm 62/fts_any.result
rm 62/index_all.result
rm 62/index_any.result
rm 63/fts_all.result
rm 63/fts_any.result
rm 63/index_all.result
rm 63/index_any.result
rm 64/fts_all.result
rm 64/fts_any.result
rm 64/index_all.result
rm 64/index_any.result
rm 65/fts_all.result
rm 65/fts_any.result
rm 65/index_all.result
rm 65/index_any.result
rm 66/fts_all.result
rm 66/fts_any.result
rm 66/index_all.result
rm 66/index_any.result
rm 67/fts_all.result
rm 67/fts_any.result
rm 67/index_all.result
rm 67/index_any.result
rm 68/fts_all.result
rm 68/fts_any.result
rm 68/index_all.result
rm 68/index_any.result
rm 69/fts_all.result
rm 69/fts_any.result
rm 69/index_all.result
rm 69/index_any.result
rm 70/fts_all.result
rm 70/fts_any.result
rm 70/index_all.result
rm 70/index_any.result
rm 71/fts_all.result
rm 71/fts_any.result
rm 71/index_all.result
rm 71/index_any.result
rm 72/fts_all.result
rm 72/fts_any.result
rm 72/index_all.result
rm 72/index_any.result
rm 73/fts_all.result
rm 73/fts_any.result
rm 73/index_all.result
rm 73/index_any.result
rm 74/fts_all.result
rm 74/fts_any.result
rm 74/index_all.result
rm 74/index_any.result
rm 75/fts_all.result
rm 75/fts_any.result
rm 75/index_all.result
rm 75/index_any.result
rm 76/fts_all.result
rm 76/fts_any.result
rm 76/index_all.result
rm 76/index_any.result
rm 77/fts_all.result
rm 77/fts_any.result
rm 77/index_all.result
rm 77/index_any.result
rm 78/fts_all.result
rm 78/fts_any.result
rm 78/index_all.result
rm 78/index_any.result
rm 79/fts_all.result
rm 79/fts_any.result
rm 79/index_all.result
rm 79/index_any.result
rm 80/fts_all.result
rm 80/fts_any.result
rm 80/index_all.result
rm 80/index_any.result
rm 81/fts_all.result
rm 81/fts_any.result
rm 81/index_all.result
rm 81/index_any.result
rm 82/fts_all.result
rm 82/fts_any.result
rm 82/index_all.result
rm 82/index_any.result
rm 83/fts_all.result
rm 83/fts_any.result
rm 83/index_all.result
rm 83/index_any.result
rm 84/fts_all.result
rm 84/fts_any.result
rm 84/index_all.result
rm 84/index_any.result
rm 85/fts_all.result
rm 85/fts_any.result
rm 85/index_all.result
rm 85/index_any.result
rm 86/fts_all.result
rm 86/fts_any.result
rm 86/index_all.result
rm 86/index_any.result
rm 87/fts_all.result
rm 87/fts_any.result
rm 87/index_all.result
rm 87/index_any.result
rm 88/fts_all.result
rm 88/fts_any.result
rm 88/index_all.result
rm 88/index_any.result
rm 89/fts_all.result
rm 89/fts_any.result
rm 89/index_all.result
rm 89/index_any.result
rm 90/fts_all.result
rm 90/fts_any.result
rm 90/index_all.result
rm 90/index_any.result
