cat 1/fts_all.result 2/fts_all.result 3/fts_all.result 4/fts_all.result 5/fts_all.result 6/fts_all.result 7/fts_all.result 8/fts_all.result 9/fts_all.result 10/fts_all.result 11/fts_all.result 12/fts_all.result 13/fts_all.result 14/fts_all.result 15/fts_all.result 16/fts_all.result 17/fts_all.result 18/fts_all.result 19/fts_all.result 20/fts_all.result 21/fts_all.result 22/fts_all.result 23/fts_all.result 24/fts_all.result 25/fts_all.result 26/fts_all.result 27/fts_all.result 28/fts_all.result 29/fts_all.result 30/fts_all.result 31/fts_all.result 32/fts_all.result 33/fts_all.result 34/fts_all.result 35/fts_all.result 36/fts_all.result 37/fts_all.result 38/fts_all.result 39/fts_all.result 40/fts_all.result 41/fts_all.result 42/fts_all.result 43/fts_all.result 44/fts_all.result 45/fts_all.result 46/fts_all.result 47/fts_all.result 48/fts_all.result 49/fts_all.result 50/fts_all.result > fts_all.result
cat 1/fts_any.result 2/fts_any.result 3/fts_any.result 4/fts_any.result 5/fts_any.result 6/fts_any.result 7/fts_any.result 8/fts_any.result 9/fts_any.result 10/fts_any.result 11/fts_any.result 12/fts_any.result 13/fts_any.result 14/fts_any.result 15/fts_any.result 16/fts_any.result 17/fts_any.result 18/fts_any.result 19/fts_any.result 20/fts_any.result 21/fts_any.result 22/fts_any.result 23/fts_any.result 24/fts_any.result 25/fts_any.result 26/fts_any.result 27/fts_any.result 28/fts_any.result 29/fts_any.result 30/fts_any.result 31/fts_any.result 32/fts_any.result 33/fts_any.result 34/fts_any.result 35/fts_any.result 36/fts_any.result 37/fts_any.result 38/fts_any.result 39/fts_any.result 40/fts_any.result 41/fts_any.result 42/fts_any.result 43/fts_any.result 44/fts_any.result 45/fts_any.result 46/fts_any.result 47/fts_any.result 48/fts_any.result 49/fts_any.result 50/fts_any.result > fts_any.result
cat 1/index_all.result 2/index_all.result 3/index_all.result 4/index_all.result 5/index_all.result 6/index_all.result 7/index_all.result 8/index_all.result 9/index_all.result 10/index_all.result 11/index_all.result 12/index_all.result 13/index_all.result 14/index_all.result 15/index_all.result 16/index_all.result 17/index_all.result 18/index_all.result 19/index_all.result 20/index_all.result 21/index_all.result 22/index_all.result 23/index_all.result 24/index_all.result 25/index_all.result 26/index_all.result 27/index_all.result 28/index_all.result 29/index_all.result 30/index_all.result 31/index_all.result 32/index_all.result 33/index_all.result 34/index_all.result 35/index_all.result 36/index_all.result 37/index_all.result 38/index_all.result 39/index_all.result 40/index_all.result 41/index_all.result 42/index_all.result 43/index_all.result 44/index_all.result 45/index_all.result 46/index_all.result 47/index_all.result 48/index_all.result 49/index_all.result 50/index_all.result > index_all.result
cat 1/index_any.result 2/index_any.result 3/index_any.result 4/index_any.result 5/index_any.result 6/index_any.result 7/index_any.result 8/index_any.result 9/index_any.result 10/index_any.result 11/index_any.result 12/index_any.result 13/index_any.result 14/index_any.result 15/index_any.result 16/index_any.result 17/index_any.result 18/index_any.result 19/index_any.result 20/index_any.result 21/index_any.result 22/index_any.result 23/index_any.result 24/index_any.result 25/index_any.result 26/index_any.result 27/index_any.result 28/index_any.result 29/index_any.result 30/index_any.result 31/index_any.result 32/index_any.result 33/index_any.result 34/index_any.result 35/index_any.result 36/index_any.result 37/index_any.result 38/index_any.result 39/index_any.result 40/index_any.result 41/index_any.result 42/index_any.result 43/index_any.result 44/index_any.result 45/index_any.result 46/index_any.result 47/index_any.result 48/index_any.result 49/index_any.result 50/index_any.result > index_any.result

rm 1/fts_all.result
rm 1/fts_any.result
rm 1/index_all.result
rm 1/index_any.result
rm 2/fts_all.result
rm 2/fts_any.result
rm 2/index_all.result
rm 2/index_any.result
rm 3/fts_all.result
rm 3/fts_any.result
rm 3/index_all.result
rm 3/index_any.result
rm 4/fts_all.result
rm 4/fts_any.result
rm 4/index_all.result
rm 4/index_any.result
rm 5/fts_all.result
rm 5/fts_any.result
rm 5/index_all.result
rm 5/index_any.result
rm 6/fts_all.result
rm 6/fts_any.result
rm 6/index_all.result
rm 6/index_any.result
rm 7/fts_all.result
rm 7/fts_any.result
rm 7/index_all.result
rm 7/index_any.result
rm 8/fts_all.result
rm 8/fts_any.result
rm 8/index_all.result
rm 8/index_any.result
rm 9/fts_all.result
rm 9/fts_any.result
rm 9/index_all.result
rm 9/index_any.result
rm 10/fts_all.result
rm 10/fts_any.result
rm 10/index_all.result
rm 10/index_any.result
rm 11/fts_all.result
rm 11/fts_any.result
rm 11/index_all.result
rm 11/index_any.result
rm 12/fts_all.result
rm 12/fts_any.result
rm 12/index_all.result
rm 12/index_any.result
rm 13/fts_all.result
rm 13/fts_any.result
rm 13/index_all.result
rm 13/index_any.result
rm 14/fts_all.result
rm 14/fts_any.result
rm 14/index_all.result
rm 14/index_any.result
rm 15/fts_all.result
rm 15/fts_any.result
rm 15/index_all.result
rm 15/index_any.result
rm 16/fts_all.result
rm 16/fts_any.result
rm 16/index_all.result
rm 16/index_any.result
rm 17/fts_all.result
rm 17/fts_any.result
rm 17/index_all.result
rm 17/index_any.result
rm 18/fts_all.result
rm 18/fts_any.result
rm 18/index_all.result
rm 18/index_any.result
rm 19/fts_all.result
rm 19/fts_any.result
rm 19/index_all.result
rm 19/index_any.result
rm 20/fts_all.result
rm 20/fts_any.result
rm 20/index_all.result
rm 20/index_any.result
rm 21/fts_all.result
rm 21/fts_any.result
rm 21/index_all.result
rm 21/index_any.result
rm 22/fts_all.result
rm 22/fts_any.result
rm 22/index_all.result
rm 22/index_any.result
rm 23/fts_all.result
rm 23/fts_any.result
rm 23/index_all.result
rm 23/index_any.result
rm 24/fts_all.result
rm 24/fts_any.result
rm 24/index_all.result
rm 24/index_any.result
rm 25/fts_all.result
rm 25/fts_any.result
rm 25/index_all.result
rm 25/index_any.result
rm 26/fts_all.result
rm 26/fts_any.result
rm 26/index_all.result
rm 26/index_any.result
rm 27/fts_all.result
rm 27/fts_any.result
rm 27/index_all.result
rm 27/index_any.result
rm 28/fts_all.result
rm 28/fts_any.result
rm 28/index_all.result
rm 28/index_any.result
rm 29/fts_all.result
rm 29/fts_any.result
rm 29/index_all.result
rm 29/index_any.result
rm 30/fts_all.result
rm 30/fts_any.result
rm 30/index_all.result
rm 30/index_any.result
rm 31/fts_all.result
rm 31/fts_any.result
rm 31/index_all.result
rm 31/index_any.result
rm 32/fts_all.result
rm 32/fts_any.result
rm 32/index_all.result
rm 32/index_any.result
rm 33/fts_all.result
rm 33/fts_any.result
rm 33/index_all.result
rm 33/index_any.result
rm 34/fts_all.result
rm 34/fts_any.result
rm 34/index_all.result
rm 34/index_any.result
rm 35/fts_all.result
rm 35/fts_any.result
rm 35/index_all.result
rm 35/index_any.result
rm 36/fts_all.result
rm 36/fts_any.result
rm 36/index_all.result
rm 36/index_any.result
rm 37/fts_all.result
rm 37/fts_any.result
rm 37/index_all.result
rm 37/index_any.result
rm 38/fts_all.result
rm 38/fts_any.result
rm 38/index_all.result
rm 38/index_any.result
rm 39/fts_all.result
rm 39/fts_any.result
rm 39/index_all.result
rm 39/index_any.result
rm 40/fts_all.result
rm 40/fts_any.result
rm 40/index_all.result
rm 40/index_any.result
rm 41/fts_all.result
rm 41/fts_any.result
rm 41/index_all.result
rm 41/index_any.result
rm 42/fts_all.result
rm 42/fts_any.result
rm 42/index_all.result
rm 42/index_any.result
rm 43/fts_all.result
rm 43/fts_any.result
rm 43/index_all.result
rm 43/index_any.result
rm 44/fts_all.result
rm 44/fts_any.result
rm 44/index_all.result
rm 44/index_any.result
rm 45/fts_all.result
rm 45/fts_any.result
rm 45/index_all.result
rm 45/index_any.result
rm 46/fts_all.result
rm 46/fts_any.result
rm 46/index_all.result
rm 46/index_any.result
rm 47/fts_all.result
rm 47/fts_any.result
rm 47/index_all.result
rm 47/index_any.result
rm 48/fts_all.result
rm 48/fts_any.result
rm 48/index_all.result
rm 48/index_any.result
rm 49/fts_all.result
rm 49/fts_any.result
rm 49/index_all.result
rm 49/index_any.result
rm 50/fts_all.result
rm 50/fts_any.result
rm 50/index_all.result
rm 50/index_any.result
